project_id = "cghzttbggklhuyqxzabq"

[functions.create-asaas-customer]
verify_jwt = true

[functions.create-asaas-payment]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.generate-recurring-charges]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.check-workout-expirations]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false
